version: '3'

services:
  contacts_nodejs:
    build: ./nodejs
    container_name: contacts_nodejs

    volumes:
      - "./app:/src/app"
      - /tmp:/tmp

    ports:
      - "8004:3000"

    networks:
        - proxy

    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.basic.frontend.rule=Host:contacts.louislabs.com"
        - "traefik.basic.port=3000"
        - "traefik.basic.protocol=http"

networks:
    proxy:
        external: true
